name: .Net

on: [push, pull_request]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v2

      - name: Run ModelTests
        runs: make modeltests

      - name: Deploy WebAPI
        run: make webapi.heroku HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}
